### ISSUE TITLE
Activate Travis build ?

### ISSUE THREAD

**Issue by samsonasik** [KejawenLab/SemartSkeleton#14]
usul: travis build diaktifkan

**Comment by ad3n** [comment]
@samsonasik boleh bantu setupnya ga om? hehehe soalnya baru pengalaman setup gitlab pipeline

**Comment by samsonasik** [comment]
boleh, kalau aktifinnya, bisa aktifin di https://travis-ci.org/ , klik "Sign in with Github" oleh repo owner/kolaborator(?), dan pilih repositories -> cek list aktifin. Saya coba di sini "Sign in with Github" ga jalan, mungkin travisnya lagi down.

Nah, kalau sudah tinggal kasih tahu saya, nanti setelah itu, saya bisa kirim pull request buat konfigurasi `.travis.yml`.

**Comment by samsonasik** [comment]
ok, "Sign in with Github" udah bisa lagi di  https://travis-ci.org/ , kalau mau saya yang setup di travis site nya jg, mungkin bisa jadikan saya member/collabolator dulu di https://github.com/orgs/KejawenLab/people

**Comment by samsonasik** [comment]
hm.., sepertinya harus punya permission khusus(owner repo/org) buat bisa aktifin ceklist di travis, kalau mas @ad3n seharusnya tinggal ceklist aja reponya:

![permissin-travis](https://user-images.githubusercontent.com/459648/55043751-25a77e00-506a-11e9-9d19-5a97094d8ae6.png)

**Comment by samsonasik** [comment]
sepertinya bisa kalau pakai "Admin" permission level di repository settingnya, ini contoh kalau pakai team, berarti buat team dulu, masukin ke permission admin, jadi ceklist di travis bisa dikelola oleh team:

![Screen Shot 2019-03-27 at 9 19 23 AM](https://user-images.githubusercontent.com/459648/55045803-c5b4d580-5071-11e9-91ab-b5dbdec71e00.png)
![Screen Shot 2019-03-27 at 9 19 44 AM](https://user-images.githubusercontent.com/459648/55045804-c5b4d580-5071-11e9-9d28-385b99f42624.png)

ref: https://help.github.com/en/articles/managing-team-access-to-an-organization-repository
