### ISSUE TITLE
run phpstan static analyzer on build

### ISSUE THREAD

**Issue by samsonasik** [KejawenLab/SemartSkeleton#22]
Jika mas @ad3n setuju, phpstan akan saya coba tambahkan. Minimal untuk `src` directory, mulai dari level 0, lanjut level sampai --level=max atau --level=7 jika bisa.

Setuju?

**Comment by ad3n** [comment]
@samsonasik: monggo mas biar makin standard

**Comment by ad3n** [comment]
#23
