### ISSUE TITLE
docker failed

### ISSUE THREAD

**Issue by anuku7** [KejawenLab/SemartSkeleton#37]
waktu jalanin docker-compose keluar error begini

`ERROR: Dockerfile parse error line 63: unknown instruction: COMPOSER`

**Comment by anuku7** [comment]
solve dengan menambah
`&&\ `  di akhir baris 62 dockerfile

**Comment by samsonasik** [comment]
@anuku7 terima kasih, sudah diupdate di https://github.com/KejawenLab/SemartSkeleton/commit/790b6b860cea59123824f5c642ee20460f244301
