### ISSUE TITLE
Tombol tambah tidak berfungsi

### ISSUE THREAD

**Issue by alfarioekaputra** [KejawenLab/SemartSkeleton#4]
Selamat siang,

saya sedang mencoba Generate Crud template, saya mengikuti tutorial di dokumentasi

begitu klik tombol tambah muncul pesan error di console "ReferenceError: formReset is not defined"

![image](https://user-images.githubusercontent.com/650641/54470592-03e20780-47dd-11e9-89d7-ca864af8df60.png)

saya hapus formReset,() tombol tambahnya berjalan normal

terima kasih

**Comment by ad3n** [comment]
Noted om, iya kayaknya ada yang kehapus

Bisa PR ga om untuk hapus formReset() aja

**Comment by alfarioekaputra** [comment]
udah saya bikin PR ya @ad3n

**Comment by ad3n** [comment]
Closed #5 thanks om @alfarioekaputra
