### ISSUE TITLE
1 form insert or update di 2 table atau lebih

### ISSUE THREAD

**Issue by kefalucky** [KejawenLab/SemartSkeleton#64]
bagaimana cara menginput atau edit data dalam 1 form ke dua  table atau 3 table

**Comment by ad3n** [comment]
@samsonasik : Bisa menggunakan entity akhir, misal relasi antara table propinsi, kebupaten, dan kecamatan. Kita mau langsung menginput ketiganya masuk ke table masing-masing

Maka cara paling mudah adalah melakukan persist pada object kecamatan dengan metode cascade persist pada konfigurasi relasinya

**Comment by samsonasik** [comment]
mas @ad3n yang tanya @kefalucky :D

**Comment by ad3n** [comment]
Wah iya... maaf-maaf salah fokus

**Comment by ad3n** [comment]
close karena ga ada response berikutnya
