### ISSUE TITLE
FOSJsRoutingBundle the route does not exist error

### ISSUE THREAD

**Issue by samsonasik** [KejawenLab/SemartSkeleton#84]
Step to reproduce:

1. Open `/admin/users/?m=user&s=fullName&d=a`
2. Klik Ubah di record
3. Tampil error di js console

![Screen Shot 2020-01-09 at 1 29 48 AM](https://user-images.githubusercontent.com/459648/72006849-1012e600-3283-11ea-95d9-7e3c9ebf7dc2.png)

**Comment by ad3n** [comment]
@samsonasik : itu yang type mime-nya text/html untuk setRoute boleh lihat response aslinya ga?

**Comment by samsonasik** [comment]
mas @ad3n dapatnya 404: 

![Screen Shot 2020-01-09 at 11 01 26 PM](https://user-images.githubusercontent.com/459648/72083252-0eedc180-3334-11ea-9b9a-8782a4bf724a.png)

**Comment by samsonasik** [comment]
sepertinya karena ada folder `js` di dalam `public`, sehingga `/js/routing` dianggap sebagai file yang dituju, bukan routing yang dideklarasi di konfigurasi, sehingga dapatnya 404

**Comment by samsonasik** [comment]
Fixed di commit https://github.com/KejawenLab/SemartSkeleton/commit/198d785c8ce9be0a2602bdffa299ad04de4fee64 dengan cara meng-"override" path routing `js/routing` menjadi `js_/routing` untuk fos js routing
