### ISSUE TITLE
Docker Installation Failed in step 32

### ISSUE THREAD

**Issue by andriawan** [KejawenLab/SemartSkeleton#90]
I try to install SemartSkeleton via docker

i found that the steps failed in step 32 (dealing with composer.json i think, but i am not sure)

did i miss something?

![image](https://user-images.githubusercontent.com/13099373/83385968-65a78500-a414-11ea-8a32-13d1bb977839.png)

**Comment by ad3n** [comment]
@andriawan : Noted om. Terima kasih

**Comment by ad3n** [comment]
@andriawan : Fix: #https://github.com/KejawenLab/SemartSkeleton/commit/1101e7373aa1509c97784205f8eb61960d4096fb

**Comment by andriawan** [comment]
@ad3n oke mas, aq coba lagi

**Comment by andriawan** [comment]
Docker step berhasil  mas @ad3n , tapi ada kendala. Saya sudah coba exec ke container app dan menjalankan bin/console server:start. Tidak ada response di host browser port 8080.

![image](https://user-images.githubusercontent.com/13099373/83537631-04b8a380-a51f-11ea-82dc-ac0c922b365f.png)

saya rasa logs aman juga

![image](https://user-images.githubusercontent.com/13099373/83537714-21ed7200-a51f-11ea-9033-a71521423d69.png)

![image](https://user-images.githubusercontent.com/13099373/83537734-2a45ad00-a51f-11ea-8aeb-e8b1e94753b7.png)

Apa ada step yang saya lewatkan ya?

**Comment by ad3n** [comment]
@andriawan : maaf portnya saya ganti ke 9876 dan dokumentasinya belum diupdate
