### ISSUE TITLE
ERROR: Service 'app' failed to build: The command '/bin/sh -c apt-get install nginx supervisor vim software-properties-common curl ca-certificates unzip -y' returned a non-zero code: 100

### ISSUE THREAD

**Issue by galihlasahido** [KejawenLab/SemartSkeleton#93]
waktu coba jalanin pake 

`docker-compose build && docker-compose up`

keluarnya error dibawah,

Reading package lists...
Building dependency tree...
Reading state information...
Package ca-certificates is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package nginx
E: Unable to locate package supervisor
E: Unable to locate package vim
E: Unable to locate package software-properties-common
E: Unable to locate package curl
E: Package 'ca-certificates' has no installation candidate
E: Unable to locate package unzip
ERROR: Service 'app' failed to build: The command '/bin/sh -c apt-get install nginx supervisor vim software-properties-common curl ca-certificates unzip -y' returned a non-zero code: 100

**Comment by ad3n** [comment]
@galihlasahido bisa dipastikan tidak untuk koneksi internetnya bagus?

Kalau boleh tau clone dari stable atau master?

Error 100 itu karena package not found tapi penyebabnya bisa karena koneksi atau memang tidak ada, cuma kalau tidak ada kayaknya ga mungkin

**Comment by bramaudi** [comment]
Saya mengalami hal serupa, sepertinya memang tidak ada paket **supervisor** di repo mirror saat ini (yaitu kartolo.sby).

Solusi dari saya yaitu ganti `http://kartolo.sby.datautama.net.id/ubuntu/` dengan `http://archive.ubuntu.com/ubuntu` pada file `docker/apt/sources.list` kemudian lakukan _build_ ulang.

Mungkin ada baiknya jika mirrorlist bawaan juga di tambahkan sebagai mirrorlist _fallback_ untuk tindakan pencegahan bug seperti ini dikemudian hari?

**Comment by ad3n** [comment]
@bramaudi use SemartApiSkeleton instead of SemarSkeleton

**Comment by ad3n** [comment]
https://github.com/KejawenLab/SemartApiSkeleton
