### ISSUE TITLE
Error on pre-installation

### ISSUE THREAD

**Issue by bramaudi** [KejawenLab/SemartSkeleton#96]
# Step to reproduce
1. Clone `https://github.com/KejawenLab/SemartSkeleton`
2. Run `docker-compose build && docker-compose up`
3. Run `docker-compose exec app bash` then execute `php bin/console semart:install` inside

# Error
![image](https://user-images.githubusercontent.com/14371119/143612527-d77accb9-7cb6-48de-b97c-690a52674cde.png)

**Comment by ad3n** [comment]
@bramaudi read the doc, you can not run like that... You need to generate pki chain

**Comment by ad3n** [comment]
@bramaudi use https://github.com/KejawenLab/SemartApiSkeleton instead of this repo
